# config sub-domains<only sub-domain> here
change_sub_domains:
  - 'hello' # hello.infot.me
  - 'world' # world.infot.me

# aliyun authorization
authorization:
  access_key_id: 'IAMasd879679mSAD9'
  access_key_secret: 'IAMasd879679mSAD9IAMasd879679mSAD9'
  current_root_domain: 'infot.me'                   # the root-domain
  region_id: 'cn-shenzhen'                          # city code, China cities default is cn-<city-full-name>

# 1. ip_provider: use access public website get current public ip
# 2. ethernet_info: use `ip addr` detect current public ip
# run_type: ip_provider
run_type: ethernet_info
ip_provider:
  # here is public ip provider(page and public ip regex extractor), u also can config more provider follow below format
  -
    provider: 'https://www.ip.cn'
    regex_pattern: '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
  -
    provider: 'http://pv.sohu.com/cityjson'
    regex_pattern: '(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

ethernet_info:
  ethernet: 'ether'
